### ISSUE TITLE
Road to 0.2 - aka "first stable release"

### ISSUE THREAD

**Issue by ddanier** [ddanier/nur#9]
I'm currently using version 0.1.x for trying out things and finding the best way to implement stuff. Version 0.2.0 should be the version that provides some stable ground to build upon and also contain all the core features. After 0.2.0 I will switch to a semver based release versioning.

Ideas I want to think about and/or implement for 0.2.0:

- [x] `nur` should not interfere with normal `nu` shell config/env. Thus maybe we should set `default-config-dir` to `$project-path/.nur`. This would also replace the current `.nurscripts` directory.
   - Seems not really possible, BUT: We can set libs and plugins dir accordingly
- [x] Refactor `main.rs` to be way more modular, should also increase testability.
- [x] ~~Maybe provide `nu_plugin_nur` command to easily register `nur` as a `nu` plugin for `nu` shell users. See #3~~
- [x] Ensure we have the right base feature set. Maybe less is more here. See #1 and #2 
- [x] Have at least some tests to ensure `nur` works from a user perspective, maybe actually call some `nur` tasks for this. Might include #6 
- [x] `nur` was tested on Linux, Mac and Windows.
- [x] Provide binaries for the most common systems. See https://github.com/nushell/nushell/blob/main/.github/workflows/release.yml for how `nu` does this
- [x] ~~Should it be possible to use plugins? Would be a local requirement - I don't really like that.~~
- [x] Which feature flags should be active? Follow nu? Do we really need dataframes?
- [x] Update docs to match current version. Document at least `env.nu` and `scripts` behaviour

**Comment by ddanier** [comment]
`0.1.12` did solve some of the tasks 😉👍

**Comment by ddanier** [comment]
Some decisions:
* I won't add a package manager, as there will be `nupm` in the future, but it is not ready yet to be used.
* I won't add a template engine for now.
* `nur` will not support plugins. There is experimental support somewhere in the code, but this will not be documented for now. Also no tests will be written to ensure it works.
* Also `nur` will not be usable as a plugin itself for now. This may be added in a future version but should not be in the initial stable release. I expect this to cause issues as the cli options change based on the current working directory and I am not sure how `nu` will handle this.

Also I did manage to run `nur` on Windows and also execute some tasks. The normal `cargo install nur` just did work. Although I had to fix the tests written in nu shell scripting.

**Comment by ddanier** [comment]
I also verified `nur` runs on Linux (Debian), so this should all be fine. Also the tests run on all three platforms now. ;-)

**Comment by ddanier** [comment]
Maybe I should remove support for the config.nu:
> What about customizing interactive shells, similar to .zshrc? By default config.nu is only loaded in interactive shells, not scripts.

From https://www.nushell.sh/book/configuration.html#configuring-nu-as-a-login-shell

**Comment by ddanier** [comment]
Release of 0.2.0 is currently happening. So I will now close this issue. :)
